trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'dockerHub'

steps:
- task: Docker@2
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
