trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'Docker Hub'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'